# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 11:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='GTIN_CD',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 13', regex='^.{13}$')]),
        ),
    ]
