# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_auto_20160323_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='COUNTRY_ISO3',
        ),
        migrations.AddField(
            model_name='country',
            name='COUNTRY_EU',
            field=models.NullBooleanField(default=False),
        ),
    ]
